source 'https://rubygems.org'

# gem 'rspec'
gem 'rspec', '~> 2.14.0'
gem 'selenium-webdriver'
gem 'sauce_whisk'
gem 'sauce'
gem 'sauce-connect'
gem 'parallel_tests'
gem 'rake'
gem 'rspec_junit_formatter'
